{"name": "Проверяем, что система вернёт ошибку, если неправильно указать Логин", "status": "broken", "statusDetails": {"message": "NameError: name 'register_new_courier_and_return_login_password' is not defined", "trace": "self = <test_courier_login.TestCourierLogin object at 0x00000134C13B8F80>\n\n    def setup_method(self):\n    \n>       self.login_pass = register_new_courier_and_return_login_password()\nE       NameError: name 'register_new_courier_and_return_login_password' is not defined\n\ntests\\test_courier_login.py:46: NameError"}, "start": 1727539564648, "stop": 1727539564648, "uuid": "f9275d8a-56a1-4914-a8f4-1e915bdf6dad", "historyId": "4c3c872251f9eb69f5d1de883ebf7f36", "testCaseId": "4c3c872251f9eb69f5d1de883ebf7f36", "fullName": "tests.test_courier_login.TestCourierLogin#test_incorrect_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_login"}, {"name": "subSuite", "value": "TestCourierLogin"}, {"name": "host", "value": "DESKTOP-AMN9CM3"}, {"name": "thread", "value": "10628-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_login"}]}